### ISSUE TITLE
Can't install using pip

### ISSUE THREAD

**Issue by KIRA009** [strawberry-graphql/strawberry#170]
I tried installing the module using pip
`pip3 install strawberry-graphql`

This was the response
```
ERROR: Could not find a version that satisfies the requirement strawberry-graphql (from versions: none)
ERROR: No matching distribution found for strawberry-graphql
```

**Comment by patrick91** [comment]
Just tried this on my server:

```
patrick in /tmp at patrick-MacBookPro
➜ python3 -m venv asd
sourcer %
patrick in /tmp at patrick-MacBookPro took 2s
➜ source ./asd/bin/activate

patrick in /tmp at patrick-MacBookPro via asd
➜ pip3 install strawberry-graphql
Collecting strawberry-graphql
  Downloading https://files.pythonhosted.org/packages/1c/ee/e2af8128006ac35afc2f7a305f5b037ccace047b986a1c88f7930b84bed2/strawberry_graphql-0.16.1-py3-none-any.whl
Collecting pygments<3.0,>=2.3 (from strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl
Collecting hupper<2.0,>=1.5 (from strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/ba/0f/fb7d8c05abec2e423e775b0b07e63793e8316cb090cb67d7c779eaef25b1/hupper-1.8.1-py2.py3-none-any.whl
Collecting click<8.0,>=7.0 (from strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting starlette==0.12.9 (from strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/67/95/2220fe5bf287e693a6430d8ee36c681b0157035b7249ec08f8fb36319d16/starlette-0.12.9.tar.gz
Collecting graphql-core<4.0.0,>=3.0.0a0 (from strawberry-graphql)
  Downloading https://files.pythonhosted.org/packages/46/8e/573b08395a240e6cf0562798c0ef75121a638bc9585b4575e52d8567fda8/graphql_core-3.0.0b1-py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 5.5MB/s
Collecting uvicorn==0.9.0 (from strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/5a/a9/2ab492155d9b76cf109c2370e201822ba3c7f4aed85f5a1b4d22907e7206/uvicorn-0.9.0.tar.gz
Collecting h11==0.8.* (from uvicorn==0.9.0->strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/f9/f3/8e4cf5fa1a3d8bda942a0b1cf92f87815494216fd439f82eb99073141ba0/h11-0.8.1-py2.py3-none-any.whl
Collecting websockets==8.* (from uvicorn==0.9.0->strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/49/af/d01b9d7a6c95d86c8f3c3df7a152f4e3d131fb1fe54facea103a3fd89ed4/websockets-8.0.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting httptools==0.0.13 (from uvicorn==0.9.0->strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/1b/03/215969db11abe8741e9c266a4cbe803a372bd86dd35fa0084c4df6d4bd00/httptools-0.0.13.tar.gz
Collecting uvloop==0.* (from uvicorn==0.9.0->strawberry-graphql)
  Using cached https://files.pythonhosted.org/packages/bb/27/83c42973ae0a27340c32170fa261f1692319371df1fb3bf054a00dd52d7c/uvloop-0.13.0-cp37-cp37m-manylinux2010_x86_64.whl
Installing collected packages: pygments, hupper, click, starlette, graphql-core, h11, websockets, httptools, uvloop, uvicorn, strawberry-graphql
  Running setup.py install for starlette ... done
  Running setup.py install for httptools ... done
  Running setup.py install for uvicorn ... done
Successfully installed click-7.0 graphql-core-3.0.0b1 h11-0.8.1 httptools-0.0.13 hupper-1.8.1 pygments-2.4.2 starlette-0.12.9 strawberry-graphql-0.16.1 uvicorn-0.9.0 uvloop-0.13.0 websockets-8.0.2
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

@KIRA009 I'm not sure how to debug this issue, but can you comment with some information about:

1. python version
2. pip version
3. os version
4. result of `pip3 config list`

hope to help!

**Comment by KIRA009** [comment]
Thanks for replying quickly. I will definitely update you with required info. 

Also looking forward to solving the `hacktober` labelled issues

**Comment by Hispar** [comment]
I'm having the same problem:
1. Python 3.6.8
2. Pip 19.0.3
3. Ubuntu 18.04.3
4. pip3 config list doesn't output anything. pip3 list output is 
`pip   19.0.3`
`setuptools 40.8.0`

**Comment by marcoacierno** [comment]
I think it might be caused by the fact that we require python 3.7?

**Comment by Hispar** [comment]
@marcoacierno thanks for the answer didn't know that. 
Maybe add a requirements line in the README will avoid this kind of errors.

**Comment by marcoacierno** [comment]
I don't think we need to restrict to python 3.7 actually, as we only use the f-strings which is available from 3.6. We can definitely change the restriction to >=3.6

**Comment by KIRA009** [comment]
> I think this might be caused by the fact that we require python 3.7?

I am running Python 3.7 in my system

**Comment by marcoacierno** [comment]
@KIRA009 Ah! I saw the same error when I tried to install strawberry on python2 that's why I connected the two things.

Can you try running the commands @patrick91 sent?

**Comment by KIRA009** [comment]
The issue is solved, it was probably something to do with python aliases in my system

Also
> Maybe add a requirements line in the README will avoid this kind of errors.

**Comment by patrick91** [comment]
@KIRA009 thanks for the feedback! Maybe you can send a PR to update the Readme? :D

I'll close this now 😊

**Comment by MoralCode** [comment]
This still appears to be an issue. i am able to reproduce it using `pyenv` to change python versions. when using python 3.6.12 i see the error from the original post, but 3.7.9 (pyenv) and 3.8.10 (system) work fine

**Comment by patrick91** [comment]
> I am able to reproduce this using `pyenv` to change python versions. when using python 3.6.12 i see the error from the original post, but 3.7.9 (pyenv) and 3.8.10 (system) work fine. Is the fix to just use a version of python 3.7? or should 3.6 also be supported by strawberry?

python 3.6 is not supported 😊

**Comment by MoralCode** [comment]
ah ok thanks for clarifying!
