### ISSUE TITLE
Fields that should be nullable complain on Null values 

### ISSUE THREAD

**Issue by nicholasbutlin** [strawberry-graphql/strawberry#2772]
I have previously been using v.0.152.0, and this bug was introduced when I upgraded to 0.176.3, and still exists in 0.177.1 

When using the pydantic integration, the following code used to return the vehicle object when the data base value of series was Null. 

```
import logging
from typing import Optional

import strawberry

from pydantic import BaseModel

logger = logging.getLogger(__name__)

class VehicleModel(BaseModel):
    account: str
    series: Optional[str] 

@strawberry.experimental.pydantic.type(model=VehicleModel, all_fields=True)
class VehicleModelType:
    pass


async def get_vehicle(identifier: str) -> Optional[VehicleModel]:
    # Database lookup
    return ...


@strawberry.type
class Query:
    @strawberry.field
    async def vehicle(self, identifier: str) -> Optional[VehicleModelType]:
        vehicle = await get_vehicle(identifier)
        return vehicle


``` 

Now however, it returns an error 
```
Cannot return null for non-nullable field VehicleModel.series
```

I would expect that it would not treat the field as Non Nullable, given that it is marked as optional. 

maybe related to #2756

**Comment by DGolubets** [comment]
I have a similar problem, without pydantic integration.
I return optional array. Strawberry complains when it's null.

**Comment by thejaminator** [comment]
sorry I'm not able to reproduce this on strawberry `0.177.3`

```
from typing import Optional

from pydantic import BaseModel

import strawberry


class VehicleModel(BaseModel):
    account: str
    series: Optional[str]


@strawberry.experimental.pydantic.type(model=VehicleModel, all_fields=True)
class VehicleModelType:
    pass


async def get_vehicle(identifier: str) -> Optional[VehicleModel]:
    # Database lookup
    return VehicleModel(account="123", series=None)


@strawberry.type
class Query:
    @strawberry.field
    async def vehicle(self, identifier: str) -> Optional[VehicleModelType]:
        vehicle = await get_vehicle(identifier)
        return vehicle


schema = strawberry.Schema(query=Query)
```

When I start the server and run a query on it, it succeeds.

<img width="855" alt="image" src="https://github.com/strawberry-graphql/strawberry/assets/30519287/142826d9-096c-41e5-b467-037cdd866f4c">


Could you also take a screenshot of the schema generated?

**Comment by nicholasbutlin** [comment]
Thanks @thejaminator 

I have found the issue - the reason ifs that I simplified the model (the real code has an Ormar model with ~65 attributes)

So a better representation of the code is actually: 

```
from typing import Optional

from pydantic import BaseModel, Field

import strawberry


class VehicleModel(BaseModel):
    account: str
    series: Optional[str] = Field(default='')


@strawberry.experimental.pydantic.type(model=VehicleModel, all_fields=True)
class VehicleModelType:
    pass


async def get_vehicle(identifier: str) -> Optional[VehicleModel]:
    # Database lookup
    return VehicleModel(account="123", series=None)


@strawberry.type
class Query:
    @strawberry.field
    async def vehicle(self, identifier: str) -> Optional[VehicleModelType]:
        vehicle = await get_vehicle(identifier)
        return vehicle


schema = strawberry.Schema(query=Query)
``` 


this fails because passing None to the Pydantic model will result in the field being set to Null, however in the creation on the Type, the default value sets the field as required, as  can be seen in the snippet below from the 

```
def get_type_for_field(field: ModelField, is_input: bool):  # noqa: ANN201
    outer_type = field.outer_type_
    replaced_type = replace_types_recursively(outer_type, is_input)

    default_defined: bool = (field.default_factory is not None
                             or field.default is not None)
    should_add_optional: bool = not (field.required or default_defined)
    if should_add_optional:
        return Optional[replaced_type]
    else:
        return replaced_type
```

I didn't expect that -  I assumed the __annotations__ would be the same, rather than derived from the Field. 

If this is the expected behaviour, I will have to revisit, otherwise, I am happy to update to something like the below and create a pull request. 

```
def get_type_for_field(field: ModelField, is_input: bool):  # noqa: ANN201
    outer_type = field.outer_type_
    replaced_type = replace_types_recursively(outer_type, is_input)
    should_add_optional: bool = not field.required

    if should_add_optional:
        return Optional[replaced_type]
    else:
        return replaced_type
```

**Comment by thejaminator** [comment]
seems like a bug! Could you create a PR please with a test that replicates
it :)

**Comment by nicholasbutlin** [comment]
hi @thejaminator I created a few failing tests, and extended a couple to account for the expected behaviour - I also had a look at the pydantic ModelField and found a surprisingly simple fix such that tests now all pass! 

PR submitted

**Comment by ndortega** [comment]
Hi @nicholasbutlin, 

Do you know if this PR was released? I'm on the latest version and am still running into issues that's preventing me from using strawberry subscriptions like how it's outlined in the [tutorial](https://strawberry.rocks/docs/general/subscriptions#subscriptions)

**Comment by nicholasbutlin** [comment]
Hi @ndortega looks like it has been merged and appears in the latest version. 
Not sure if the subscription is a related issue.

**Comment by thejaminator** [comment]
> Hi @nicholasbutlin,
> 
> Do you know if this PR was released? I'm on the latest version and am still running into issues that's preventing me from using strawberry subscriptions like how it's outlined in the [tutorial](https://strawberry.rocks/docs/general/subscriptions#subscriptions)

Hi @ndortega, could you open a separate issue please?

**Comment by thejaminator** [comment]
fixed with https://github.com/strawberry-graphql/strawberry/pull/2782

**Comment by ndortega** [comment]
> > Hi @nicholasbutlin,
> > Do you know if this PR was released? I'm on the latest version and am still running into issues that's preventing me from using strawberry subscriptions like how it's outlined in the [tutorial](https://strawberry.rocks/docs/general/subscriptions#subscriptions)
> 
> Hi @ndortega, could you open a separate issue please?

Hi @thejaminator, 

This same exact issue is already open here since May 5th: https://github.com/strawberry-graphql/strawberry/issues/2756
It looks like it's just been lost in weeds and I wanted to make sure it got some attention.

**Comment by zagortenej024** [comment]
Yup, this is still not working for subscriptions. I've tried following the official docs and got the same error as in https://github.com/strawberry-graphql/strawberry/issues/2756. I even tried the latest version, `0.192.2` at the moment.

**Comment by patrick91** [comment]
@zagortenej024 could open a new issue with a reproduction? I just tested #2756 again and it works for me :)

**Comment by ndortega** [comment]
> @zagortenej024 could open a new issue with a reproduction? I just tested #2756 again and it works for me :)

Hi @patrick91, 

I've reopened this issue and added my details to the issue here: https://github.com/strawberry-graphql/strawberry/issues/2927 
Let me know if you need any additional information to debug this, thanks!
